version: '3'

volumes:
  postgres_data:
      driver: local
      
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - 8080:8080
    command: 
      - start-dev
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
      
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8000:80"

  keycloakinit:
    build:
      context: ./keycloak
      dockerfile: keyinit
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - keycloak
  

     

