version: '3'

volumes:
  postgres_data:
      driver: local
      
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    restart: always
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - 8080:8080
    command: 
      - start-dev
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
      
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8000:80"
    volumes:
      - /home/petekape/Desktop/projects/Eshop/eShop/frontend/src:/usr/local/apache2/htdocs/

  product-service:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=backend_db
      - POSTGRES_PORT=5431
      - POSTGRES_DB=products_database
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    depends_on:
      - backend_db
    command: ["npm", "run", "migrate"]
      
  backend_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=products_database
      - POSTGRES_USER= db_user
      - POSTGRES_PASSWORD= db_password
    ports:
      - 5431:5431 

  backend_db_migrate:
    image: postgres:latest
    environment:
      - POSTGRES_DB=products_database
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "listen_addresses=*"]
      
  

     

